version: '3.8'

services:
  db:
    restart: always
    image: "postgres:14.1"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5432:5432"

  app:
    build: ./
    command: ./app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
